services:
  db:
    image: postgres:17
    container_name: smart-city-parking-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - smart-city-network

  backend:
    build: ./backend
    container_name: smart-city-parking-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/app/api
      - ./backend/smart_city_parking:/app/smart_city_parking
      - ./backend/manage.py:/app/manage.py
      - ./backend/requirements.txt:/app/requirements.txt
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ALLOWED_HOSTS=${API_HOST}
      - CORS_ALLOWED_ORIGINS=${API_URL}
    networks:
      - smart-city-network
    restart: unless-stopped

  frontend:
    build:
      context: ./smartparking
      dockerfile: Dockerfile.dev
    container_name: smart-city-parking-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./smartparking/src:/app/src
      - ./smartparking/public:/app/public
      - ./smartparking/package.json:/app/package.json
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${API_URL}
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
      - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
      - REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - smart-city-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  smart-city-network:
    driver: bridge
